truncate table ImpressionLogCampaignGenre;
truncate table ImpressionLogCampaignPeriod;
truncate table ImpressionLogCampaignRegion;
truncate table ImpressionLogGenre;
truncate table ImpressionLogPeriod;
truncate table ImpressionLogRegion;